# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mihir/Coding/tsa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mihir/Coding/tsa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihir/Coding/tsa/CMakeFiles /home/mihir/Coding/tsa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mihir/Coding/tsa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tsa

# Build rule for target.
tsa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsa
.PHONY : tsa

# fast build rule for target.
tsa/fast:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/build
.PHONY : tsa/fast

src/game/game.o: src/game/game.cpp.o

.PHONY : src/game/game.o

# target to build an object file
src/game/game.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/game.cpp.o
.PHONY : src/game/game.cpp.o

src/game/game.i: src/game/game.cpp.i

.PHONY : src/game/game.i

# target to preprocess a source file
src/game/game.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/game.cpp.i
.PHONY : src/game/game.cpp.i

src/game/game.s: src/game/game.cpp.s

.PHONY : src/game/game.s

# target to generate assembly for a file
src/game/game.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/game.cpp.s
.PHONY : src/game/game.cpp.s

src/game/game_states.o: src/game/game_states.cpp.o

.PHONY : src/game/game_states.o

# target to build an object file
src/game/game_states.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/game_states.cpp.o
.PHONY : src/game/game_states.cpp.o

src/game/game_states.i: src/game/game_states.cpp.i

.PHONY : src/game/game_states.i

# target to preprocess a source file
src/game/game_states.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/game_states.cpp.i
.PHONY : src/game/game_states.cpp.i

src/game/game_states.s: src/game/game_states.cpp.s

.PHONY : src/game/game_states.s

# target to generate assembly for a file
src/game/game_states.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/game_states.cpp.s
.PHONY : src/game/game_states.cpp.s

src/game/manager/item_manager.o: src/game/manager/item_manager.cpp.o

.PHONY : src/game/manager/item_manager.o

# target to build an object file
src/game/manager/item_manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/item_manager.cpp.o
.PHONY : src/game/manager/item_manager.cpp.o

src/game/manager/item_manager.i: src/game/manager/item_manager.cpp.i

.PHONY : src/game/manager/item_manager.i

# target to preprocess a source file
src/game/manager/item_manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/item_manager.cpp.i
.PHONY : src/game/manager/item_manager.cpp.i

src/game/manager/item_manager.s: src/game/manager/item_manager.cpp.s

.PHONY : src/game/manager/item_manager.s

# target to generate assembly for a file
src/game/manager/item_manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/item_manager.cpp.s
.PHONY : src/game/manager/item_manager.cpp.s

src/game/manager/manager.o: src/game/manager/manager.cpp.o

.PHONY : src/game/manager/manager.o

# target to build an object file
src/game/manager/manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/manager.cpp.o
.PHONY : src/game/manager/manager.cpp.o

src/game/manager/manager.i: src/game/manager/manager.cpp.i

.PHONY : src/game/manager/manager.i

# target to preprocess a source file
src/game/manager/manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/manager.cpp.i
.PHONY : src/game/manager/manager.cpp.i

src/game/manager/manager.s: src/game/manager/manager.cpp.s

.PHONY : src/game/manager/manager.s

# target to generate assembly for a file
src/game/manager/manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/manager.cpp.s
.PHONY : src/game/manager/manager.cpp.s

src/game/manager/manager_manager.o: src/game/manager/manager_manager.cpp.o

.PHONY : src/game/manager/manager_manager.o

# target to build an object file
src/game/manager/manager_manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/manager_manager.cpp.o
.PHONY : src/game/manager/manager_manager.cpp.o

src/game/manager/manager_manager.i: src/game/manager/manager_manager.cpp.i

.PHONY : src/game/manager/manager_manager.i

# target to preprocess a source file
src/game/manager/manager_manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/manager_manager.cpp.i
.PHONY : src/game/manager/manager_manager.cpp.i

src/game/manager/manager_manager.s: src/game/manager/manager_manager.cpp.s

.PHONY : src/game/manager/manager_manager.s

# target to generate assembly for a file
src/game/manager/manager_manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/manager/manager_manager.cpp.s
.PHONY : src/game/manager/manager_manager.cpp.s

src/game/object/game_item.o: src/game/object/game_item.cpp.o

.PHONY : src/game/object/game_item.o

# target to build an object file
src/game/object/game_item.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/object/game_item.cpp.o
.PHONY : src/game/object/game_item.cpp.o

src/game/object/game_item.i: src/game/object/game_item.cpp.i

.PHONY : src/game/object/game_item.i

# target to preprocess a source file
src/game/object/game_item.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/object/game_item.cpp.i
.PHONY : src/game/object/game_item.cpp.i

src/game/object/game_item.s: src/game/object/game_item.cpp.s

.PHONY : src/game/object/game_item.s

# target to generate assembly for a file
src/game/object/game_item.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/game/object/game_item.cpp.s
.PHONY : src/game/object/game_item.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sdl/renderer.o: src/sdl/renderer.cpp.o

.PHONY : src/sdl/renderer.o

# target to build an object file
src/sdl/renderer.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/renderer.cpp.o
.PHONY : src/sdl/renderer.cpp.o

src/sdl/renderer.i: src/sdl/renderer.cpp.i

.PHONY : src/sdl/renderer.i

# target to preprocess a source file
src/sdl/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/renderer.cpp.i
.PHONY : src/sdl/renderer.cpp.i

src/sdl/renderer.s: src/sdl/renderer.cpp.s

.PHONY : src/sdl/renderer.s

# target to generate assembly for a file
src/sdl/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/renderer.cpp.s
.PHONY : src/sdl/renderer.cpp.s

src/sdl/texture.o: src/sdl/texture.cpp.o

.PHONY : src/sdl/texture.o

# target to build an object file
src/sdl/texture.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/texture.cpp.o
.PHONY : src/sdl/texture.cpp.o

src/sdl/texture.i: src/sdl/texture.cpp.i

.PHONY : src/sdl/texture.i

# target to preprocess a source file
src/sdl/texture.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/texture.cpp.i
.PHONY : src/sdl/texture.cpp.i

src/sdl/texture.s: src/sdl/texture.cpp.s

.PHONY : src/sdl/texture.s

# target to generate assembly for a file
src/sdl/texture.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/texture.cpp.s
.PHONY : src/sdl/texture.cpp.s

src/sdl/window.o: src/sdl/window.cpp.o

.PHONY : src/sdl/window.o

# target to build an object file
src/sdl/window.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/window.cpp.o
.PHONY : src/sdl/window.cpp.o

src/sdl/window.i: src/sdl/window.cpp.i

.PHONY : src/sdl/window.i

# target to preprocess a source file
src/sdl/window.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/window.cpp.i
.PHONY : src/sdl/window.cpp.i

src/sdl/window.s: src/sdl/window.cpp.s

.PHONY : src/sdl/window.s

# target to generate assembly for a file
src/sdl/window.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/sdl/window.cpp.s
.PHONY : src/sdl/window.cpp.s

src/ui/background/background.o: src/ui/background/background.cpp.o

.PHONY : src/ui/background/background.o

# target to build an object file
src/ui/background/background.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/background/background.cpp.o
.PHONY : src/ui/background/background.cpp.o

src/ui/background/background.i: src/ui/background/background.cpp.i

.PHONY : src/ui/background/background.i

# target to preprocess a source file
src/ui/background/background.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/background/background.cpp.i
.PHONY : src/ui/background/background.cpp.i

src/ui/background/background.s: src/ui/background/background.cpp.s

.PHONY : src/ui/background/background.s

# target to generate assembly for a file
src/ui/background/background.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/background/background.cpp.s
.PHONY : src/ui/background/background.cpp.s

src/ui/background/background_manager.o: src/ui/background/background_manager.cpp.o

.PHONY : src/ui/background/background_manager.o

# target to build an object file
src/ui/background/background_manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/background/background_manager.cpp.o
.PHONY : src/ui/background/background_manager.cpp.o

src/ui/background/background_manager.i: src/ui/background/background_manager.cpp.i

.PHONY : src/ui/background/background_manager.i

# target to preprocess a source file
src/ui/background/background_manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/background/background_manager.cpp.i
.PHONY : src/ui/background/background_manager.cpp.i

src/ui/background/background_manager.s: src/ui/background/background_manager.cpp.s

.PHONY : src/ui/background/background_manager.s

# target to generate assembly for a file
src/ui/background/background_manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/background/background_manager.cpp.s
.PHONY : src/ui/background/background_manager.cpp.s

src/ui/components/button/button.o: src/ui/components/button/button.cpp.o

.PHONY : src/ui/components/button/button.o

# target to build an object file
src/ui/components/button/button.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/button/button.cpp.o
.PHONY : src/ui/components/button/button.cpp.o

src/ui/components/button/button.i: src/ui/components/button/button.cpp.i

.PHONY : src/ui/components/button/button.i

# target to preprocess a source file
src/ui/components/button/button.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/button/button.cpp.i
.PHONY : src/ui/components/button/button.cpp.i

src/ui/components/button/button.s: src/ui/components/button/button.cpp.s

.PHONY : src/ui/components/button/button.s

# target to generate assembly for a file
src/ui/components/button/button.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/button/button.cpp.s
.PHONY : src/ui/components/button/button.cpp.s

src/ui/components/button/button_manager.o: src/ui/components/button/button_manager.cpp.o

.PHONY : src/ui/components/button/button_manager.o

# target to build an object file
src/ui/components/button/button_manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/button/button_manager.cpp.o
.PHONY : src/ui/components/button/button_manager.cpp.o

src/ui/components/button/button_manager.i: src/ui/components/button/button_manager.cpp.i

.PHONY : src/ui/components/button/button_manager.i

# target to preprocess a source file
src/ui/components/button/button_manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/button/button_manager.cpp.i
.PHONY : src/ui/components/button/button_manager.cpp.i

src/ui/components/button/button_manager.s: src/ui/components/button/button_manager.cpp.s

.PHONY : src/ui/components/button/button_manager.s

# target to generate assembly for a file
src/ui/components/button/button_manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/button/button_manager.cpp.s
.PHONY : src/ui/components/button/button_manager.cpp.s

src/ui/components/component_manager.o: src/ui/components/component_manager.cpp.o

.PHONY : src/ui/components/component_manager.o

# target to build an object file
src/ui/components/component_manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/component_manager.cpp.o
.PHONY : src/ui/components/component_manager.cpp.o

src/ui/components/component_manager.i: src/ui/components/component_manager.cpp.i

.PHONY : src/ui/components/component_manager.i

# target to preprocess a source file
src/ui/components/component_manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/component_manager.cpp.i
.PHONY : src/ui/components/component_manager.cpp.i

src/ui/components/component_manager.s: src/ui/components/component_manager.cpp.s

.PHONY : src/ui/components/component_manager.s

# target to generate assembly for a file
src/ui/components/component_manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/component_manager.cpp.s
.PHONY : src/ui/components/component_manager.cpp.s

src/ui/components/ui_component.o: src/ui/components/ui_component.cpp.o

.PHONY : src/ui/components/ui_component.o

# target to build an object file
src/ui/components/ui_component.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/ui_component.cpp.o
.PHONY : src/ui/components/ui_component.cpp.o

src/ui/components/ui_component.i: src/ui/components/ui_component.cpp.i

.PHONY : src/ui/components/ui_component.i

# target to preprocess a source file
src/ui/components/ui_component.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/ui_component.cpp.i
.PHONY : src/ui/components/ui_component.cpp.i

src/ui/components/ui_component.s: src/ui/components/ui_component.cpp.s

.PHONY : src/ui/components/ui_component.s

# target to generate assembly for a file
src/ui/components/ui_component.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/components/ui_component.cpp.s
.PHONY : src/ui/components/ui_component.cpp.s

src/ui/slide/slide.o: src/ui/slide/slide.cpp.o

.PHONY : src/ui/slide/slide.o

# target to build an object file
src/ui/slide/slide.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/slide/slide.cpp.o
.PHONY : src/ui/slide/slide.cpp.o

src/ui/slide/slide.i: src/ui/slide/slide.cpp.i

.PHONY : src/ui/slide/slide.i

# target to preprocess a source file
src/ui/slide/slide.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/slide/slide.cpp.i
.PHONY : src/ui/slide/slide.cpp.i

src/ui/slide/slide.s: src/ui/slide/slide.cpp.s

.PHONY : src/ui/slide/slide.s

# target to generate assembly for a file
src/ui/slide/slide.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/slide/slide.cpp.s
.PHONY : src/ui/slide/slide.cpp.s

src/ui/slide/slide_manager.o: src/ui/slide/slide_manager.cpp.o

.PHONY : src/ui/slide/slide_manager.o

# target to build an object file
src/ui/slide/slide_manager.cpp.o:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/slide/slide_manager.cpp.o
.PHONY : src/ui/slide/slide_manager.cpp.o

src/ui/slide/slide_manager.i: src/ui/slide/slide_manager.cpp.i

.PHONY : src/ui/slide/slide_manager.i

# target to preprocess a source file
src/ui/slide/slide_manager.cpp.i:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/slide/slide_manager.cpp.i
.PHONY : src/ui/slide/slide_manager.cpp.i

src/ui/slide/slide_manager.s: src/ui/slide/slide_manager.cpp.s

.PHONY : src/ui/slide/slide_manager.s

# target to generate assembly for a file
src/ui/slide/slide_manager.cpp.s:
	$(MAKE) -f CMakeFiles/tsa.dir/build.make CMakeFiles/tsa.dir/src/ui/slide/slide_manager.cpp.s
.PHONY : src/ui/slide/slide_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tsa"
	@echo "... edit_cache"
	@echo "... src/game/game.o"
	@echo "... src/game/game.i"
	@echo "... src/game/game.s"
	@echo "... src/game/game_states.o"
	@echo "... src/game/game_states.i"
	@echo "... src/game/game_states.s"
	@echo "... src/game/manager/item_manager.o"
	@echo "... src/game/manager/item_manager.i"
	@echo "... src/game/manager/item_manager.s"
	@echo "... src/game/manager/manager.o"
	@echo "... src/game/manager/manager.i"
	@echo "... src/game/manager/manager.s"
	@echo "... src/game/manager/manager_manager.o"
	@echo "... src/game/manager/manager_manager.i"
	@echo "... src/game/manager/manager_manager.s"
	@echo "... src/game/object/game_item.o"
	@echo "... src/game/object/game_item.i"
	@echo "... src/game/object/game_item.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sdl/renderer.o"
	@echo "... src/sdl/renderer.i"
	@echo "... src/sdl/renderer.s"
	@echo "... src/sdl/texture.o"
	@echo "... src/sdl/texture.i"
	@echo "... src/sdl/texture.s"
	@echo "... src/sdl/window.o"
	@echo "... src/sdl/window.i"
	@echo "... src/sdl/window.s"
	@echo "... src/ui/background/background.o"
	@echo "... src/ui/background/background.i"
	@echo "... src/ui/background/background.s"
	@echo "... src/ui/background/background_manager.o"
	@echo "... src/ui/background/background_manager.i"
	@echo "... src/ui/background/background_manager.s"
	@echo "... src/ui/components/button/button.o"
	@echo "... src/ui/components/button/button.i"
	@echo "... src/ui/components/button/button.s"
	@echo "... src/ui/components/button/button_manager.o"
	@echo "... src/ui/components/button/button_manager.i"
	@echo "... src/ui/components/button/button_manager.s"
	@echo "... src/ui/components/component_manager.o"
	@echo "... src/ui/components/component_manager.i"
	@echo "... src/ui/components/component_manager.s"
	@echo "... src/ui/components/ui_component.o"
	@echo "... src/ui/components/ui_component.i"
	@echo "... src/ui/components/ui_component.s"
	@echo "... src/ui/slide/slide.o"
	@echo "... src/ui/slide/slide.i"
	@echo "... src/ui/slide/slide.s"
	@echo "... src/ui/slide/slide_manager.o"
	@echo "... src/ui/slide/slide_manager.i"
	@echo "... src/ui/slide/slide_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

